package com.example.weatherapplication.Map.MapView

import com.example.weatherapplication.Model.FavouriteCityModel.MyApplicationFavouriteCityModel.Model_FavouriteCity

interface OnFavouriteCityClickListenerInterface {

    fun onClick_insertFavouriteCityToFavouriteActivity_InFavouriteCityClickListenerInterface(city: Model_FavouriteCity)


}